<?php
/**
 * @file
 * Code for the Drush Webservice feature.
 */

include_once 'drushweb.features.inc';

/**
 * Implements hook_services_resources().
 */
function drushweb_services_resources() {
  return array(
    'drush' => array(
      'actions' => array(
        'execute' => array(
          'callback' => 'drushweb_execute',
          'access arguments' => array('oauth register consumers in drushweb'),
          'help' => t('Execute a Drush command.'),
          'args' => array(
            array(
              'name' => 'command',
              'optional' => FALSE,
              'source' => 'data',
              'description' => t('The Drush command to execute.'),
              'type' => 'string',
            ),
          ),
        ),
      ),
    ),
  );
}

/**
 * Implements hook_libraries_info.
 */
function drushweb_libraries_info() {
  $libraries['drush'] = array(
    'name' => 'Drush',
    'vendor url' => 'http://drush.org',
    'download url' => 'https://github.com/drush-ops/drush',
    'version arguments' => array(
      'file' => 'drush.info',
      'pattern' => '@drush_version=([0-9\.a-z]+)@',
      'lines' => 5,
    ),
  );
  return $libraries;
}

/**
 * Webservice callback.
 *
 * Execute a Drush command and return output.
 */
function drushweb_execute($cmd) {
  // Locate Drush.
  if (!($library = libraries_detect('drush')) || empty($library['installed'])) {
    return $library['error message'];
  }
  $bin = DRUPAL_ROOT . '/' . libraries_get_path('drush') . '/drush.php';
  
  // Sanitize command.
  $parts = explode(' ', $cmd);
  foreach ($parts as &$part) {
    $part = escapeshellarg($part);
  }
  $cmd = implode(' ', $parts);

  // Execute command and return output.
  // --strict=0 allows to pass --drushweb=y despite it is unknown from the command.
  ob_start();
  print shell_exec("$bin $cmd --drushweb=y --strict=0 2>&1");
  return ob_get_clean();
}

