<?php
/**
 * @file
 * Code for the Drush Remote Server feature.
 */

include_once 'drush_remote_server.features.inc';

/**
 * Implements hook_permission().
 */
function drush_remote_server_permission() {
  return array(
    'use drush remotely' => array(
      'title' => 'Execute a Drush command remotely',
    ),
  );
}

/**
 * Implements hook_services_resources().
 */
function drush_remote_server_services_resources() {
  return array(
    'drush' => array(
      'actions' => array(
        'execute' => array(
          'callback' => '_drush_remote_server_execute',
          'access arguments' => array('use drush remotely'),
          'help' => t('Execute a Drush command.'),
          'args' => array(
            array(
              'name' => 'command',
              'optional' => FALSE,
              'source' => 'data',
              'description' => t('The Drush command to execute.'),
              'type' => 'string',
            ),
          ),
        ),
      ),
    ),
  );
}

/**
 * Webservice callback.
 *
 * Execute a Drush command and return output.
 */
function _drush_remote_server_execute($command) {
  // TODO status report = warning if drush not in libraries
  // TODO dep = libraries
  // TODO use libraries API
  $drush = '/var/www/d7_features/sites/all/libraries/drush/drush.php';
  ob_start();
  system("$drush $command");
  return ob_get_clean();
}

// TODO see txt file on desktop
// TODO set perm
